/**
 * JWT License Validator
 * 
 * Handles JWT-based license verification with RSA signature validation.
 * Uses RS256 (asymmetric) algorithm - public key embedded, private key kept by admin.
 */

const fs = require('fs');
const path = require('path');
const jwt = require('jsonwebtoken');
const { app } = require('electron');
const { getMachineCode } = require('./machineId');
const { appendLog } = require('../logging/logger');

// ═══════════════════════════════════════════════════════════════════════
// EMBEDDED PUBLIC KEY (safe to commit to Git)
// Generated by scripts/generate-keypair.js
// Private key is kept offline by admin for JWT signing
// ═══════════════════════════════════════════════════════════════════════
const PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArSyUalTfzMvI8f6J2MIF
tnam2Mu60/VbAOu7KIGy92zq/t6UFAh1hVsQ9wMdW7rUZNMm+6SvMT77r7TkIJ0V
+YEp/LyptjD3s4Dr+UzbvMCagknlb9lpU+0J2UQahvxc1L5Ju4NAK75mpWKsbx2m
gU2aGc14y/1oN5eVnyQiHku/v9eS1EBvzQPPSxGndxQ3HZwnQaP39XYAlh0O6qMZ
dq6LEcgo9TqIU7RGi5yVv4Z1l3xy8pYZFQ0wB/xCf2KzHtOc1VfGxaD9XWZ6GRUE
HOrxx2wB7MBszBPLF627jthGz/gNQxSYX7sWmDSMxDF+mTvS33K/vlCGtAqXuiln
vQIDAQAB
-----END PUBLIC KEY-----`;

// License tier configuration
const TIER_CONFIG = {
  free: {
    maxProfiles: 5,
    features: []
  },
  pro: {
    maxProfiles: -1, // unlimited
    features: ['unlimited_profiles', 'api_access', 'automation', 'priority_support']
  }
};

/**
 * Get path to license.json file
 */
function getLicensePath() {
  try {
    return path.join(app.getPath('userData'), 'license.json');
  } catch {
    return path.join(__dirname, '../../data/license.json');
  }
}

/**
 * Verify JWT license token
 * 
 * @param {string} jwtString - JWT token to verify
 * @returns {Object} { valid: boolean, payload?: object, error?: string }
 */
function verifyJwtLicense(jwtString) {
  try {
    if (!jwtString || typeof jwtString !== 'string') {
      return { valid: false, error: 'JWT token is required' };
    }

    const trimmed = jwtString.trim();
    if (!trimmed) {
      return { valid: false, error: 'JWT token is empty' };
    }

    // Verify signature and decode payload
    let payload;
    try {
      payload = jwt.verify(trimmed, PUBLIC_KEY, { algorithms: ['RS256'] });
    } catch (err) {
      if (err.name === 'TokenExpiredError') {
        return { valid: false, error: 'License has expired', expired: true };
      }
      if (err.name === 'JsonWebTokenError') {
        return { valid: false, error: 'Invalid JWT signature' };
      }
      return { valid: false, error: `JWT verification failed: ${err.message}` };
    }

    // Validate required fields
    if (!payload.machineCode) {
      return { valid: false, error: 'JWT missing machineCode' };
    }
    if (!payload.tier) {
      return { valid: false, error: 'JWT missing tier' };
    }
    if (!payload.expiresAt) {
      return { valid: false, error: 'JWT missing expiresAt' };
    }

    // Check machine code match
    const localMachineCode = getMachineCode();
    const jwtMachineCode = String(payload.machineCode).trim();
    const localNormalized = localMachineCode.replace(/\s/g, '').toUpperCase();
    const jwtNormalized = jwtMachineCode.replace(/\s/g, '').toUpperCase();

    if (localNormalized !== jwtNormalized) {
      appendLog('system', `License machine mismatch: local=${localMachineCode}, jwt=${jwtMachineCode}`);
      return { 
        valid: false, 
        error: 'This license is for a different machine',
        machineCodeMismatch: true
      };
    }

    // Check expiry
    const now = Math.floor(Date.now() / 1000);
    if (payload.expiresAt <= now) {
      return { 
        valid: false, 
        error: 'License has expired',
        expired: true,
        expiresAt: new Date(payload.expiresAt * 1000).toISOString()
      };
    }

    // All checks passed
    appendLog('system', `License verified: tier=${payload.tier}, expires=${new Date(payload.expiresAt * 1000).toISOString()}`);
    
    return {
      valid: true,
      payload: {
        machineCode: payload.machineCode,
        tier: payload.tier || 'free',
        maxProfiles: payload.maxProfiles ?? TIER_CONFIG[payload.tier]?.maxProfiles ?? 5,
        features: payload.features || TIER_CONFIG[payload.tier]?.features || [],
        issuedAt: payload.issuedAt,
        expiresAt: payload.expiresAt,
        expiresAtDate: new Date(payload.expiresAt * 1000).toISOString()
      }
    };

  } catch (error) {
    appendLog('system', `JWT verification error: ${error.message}`);
    return { valid: false, error: `Verification error: ${error.message}` };
  }
}

/**
 * Check if license is expired
 * 
 * @param {Object} payload - Decoded JWT payload
 * @returns {boolean} true if expired
 */
function checkLicenseExpiry(payload) {
  if (!payload || !payload.expiresAt) return true;
  const now = Math.floor(Date.now() / 1000);
  return payload.expiresAt <= now;
}

/**
 * Check if payload machineCode matches local machine
 * 
 * @param {Object} payload - Decoded JWT payload
 * @returns {boolean} true if matches
 */
function matchesMachineCode(payload) {
  if (!payload || !payload.machineCode) return false;
  const local = getMachineCode().replace(/\s/g, '').toUpperCase();
  const jwt = String(payload.machineCode).replace(/\s/g, '').toUpperCase();
  return local === jwt;
}

/**
 * Get days until expiry
 * 
 * @param {number} expiresAt - Unix timestamp
 * @returns {number} Days remaining (negative if expired)
 */
function getDaysUntilExpiry(expiresAt) {
  const now = Math.floor(Date.now() / 1000);
  const secondsRemaining = expiresAt - now;
  return Math.floor(secondsRemaining / (24 * 3600));
}

/**
 * Save valid license to disk
 * 
 * @param {string} jwtString - Valid JWT token
 * @param {Object} payload - Decoded payload
 * @returns {boolean} Success status
 */
function saveLicenseToDisk(jwtString, payload) {
  try {
    const licensePath = getLicensePath();
    const dir = path.dirname(licensePath);
    
    // Ensure directory exists
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const licenseData = {
      jwt: jwtString.trim(),
      tier: payload.tier,
      maxProfiles: payload.maxProfiles,
      features: payload.features || [],
      machineCode: payload.machineCode,
      issuedAt: new Date(payload.issuedAt * 1000).toISOString(),
      expiresAt: new Date(payload.expiresAt * 1000).toISOString(),
      activatedAt: new Date().toISOString()
    };

    // Atomic write pattern
    const tempPath = licensePath + '.tmp';
    fs.writeFileSync(tempPath, JSON.stringify(licenseData, null, 2), 'utf8');
    fs.renameSync(tempPath, licensePath);

    appendLog('system', `License saved: tier=${payload.tier}, expires=${licenseData.expiresAt}`);
    return true;

  } catch (error) {
    appendLog('system', `Failed to save license: ${error.message}`);
    return false;
  }
}

/**
 * Load and verify license from disk
 * 
 * @returns {Object} { valid: boolean, tier: string, maxProfiles: number, expiresAt: string, features: [], error?: string }
 */
function loadLicenseFromDisk() {
  try {
    const licensePath = getLicensePath();

    if (!fs.existsSync(licensePath)) {
      return {
        valid: false,
        tier: 'free',
        maxProfiles: 5,
        features: [],
        error: 'No license file found'
      };
    }

    const content = fs.readFileSync(licensePath, 'utf8');
    const data = JSON.parse(content);

    if (!data.jwt) {
      return {
        valid: false,
        tier: 'free',
        maxProfiles: 5,
        features: [],
        error: 'License file missing JWT'
      };
    }

    // Re-verify JWT on every load (checks signature + expiry)
    const result = verifyJwtLicense(data.jwt);

    if (!result.valid) {
      // License invalid or expired → return free tier
      appendLog('system', `License invalid on load: ${result.error}`);
      return {
        valid: false,
        tier: 'free',
        maxProfiles: 5,
        features: [],
        expired: result.expired,
        error: result.error
      };
    }

    // Valid license
    const daysRemaining = getDaysUntilExpiry(result.payload.expiresAt);
    
    return {
      valid: true,
      tier: result.payload.tier,
      maxProfiles: result.payload.maxProfiles,
      features: result.payload.features,
      expiresAt: result.payload.expiresAtDate,
      daysRemaining,
      nearExpiry: daysRemaining <= 7 && daysRemaining > 0
    };

  } catch (error) {
    appendLog('system', `Failed to load license: ${error.message}`);
    return {
      valid: false,
      tier: 'free',
      maxProfiles: 5,
      features: [],
      error: `Load error: ${error.message}`
    };
  }
}

/**
 * Get current license tier (for profile limit enforcement)
 * 
 * @returns {Object} { tier: string, maxProfiles: number, features: [] }
 */
function getLicenseTier() {
  const license = loadLicenseFromDisk();
  return {
    tier: license.tier || 'free',
    maxProfiles: license.maxProfiles || 5,
    features: license.features || []
  };
}

/**
 * Deactivate license (delete license.json)
 * 
 * @returns {boolean} Success status
 */
function deactivateLicense() {
  try {
    const licensePath = getLicensePath();
    if (fs.existsSync(licensePath)) {
      fs.unlinkSync(licensePath);
      appendLog('system', 'License deactivated');
    }
    return true;
  } catch (error) {
    appendLog('system', `Failed to deactivate license: ${error.message}`);
    return false;
  }
}

module.exports = {
  verifyJwtLicense,
  checkLicenseExpiry,
  matchesMachineCode,
  saveLicenseToDisk,
  loadLicenseFromDisk,
  getLicenseTier,
  deactivateLicense,
  getDaysUntilExpiry
};
